[General]
SyntaxVersion=2
BeginHotkey=70
BeginHotkeyMod=6
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=3a9736f7-095a-405d-9a3c-e838c25c403b
Description=frac
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
KeyUp "Ctrl", 1
KeyUp "Alt", 1
KeyUp "F", 1
SayString "\frac{}{}"
KeyPress "Left", 3
